### ISSUE TITLE
ip filter cuts off on 'link-netnsid'

### ISSUE THREAD

**Issue by C0rn3j** [garabik/grc#180]
![image](https://user-images.githubusercontent.com/1641362/115433992-76b5dc00-a208-11eb-87a8-bd131d778fa2.png)

The ip filter seems to weirdly only match half of link-netnsid, as seen in the screenshot.

---

![image](https://user-images.githubusercontent.com/1641362/115433882-54bc5980-a208-11eb-8d38-618f61b4e1e7.png)

Side note, I've been curious since ip has its own -c color flag, was there any effort to fix that one up directly in ip instead?

I can see that it doesn't highlight UNKNOWN state but it does UP or DOWN, which is weird.

**Comment by garabik** [comment]
Thanks for noticing, it was a simple typo, fixed in c81ae202b1d3dfc5cbe480d3cea000102ccd4c23. As for the `ip -c`, I have of course no connection to that - but I assume `UP` and `DOWN` were deemed more "noticeable" than `UNKNOWN` (which likely appears mostly, if not exclusively, on the loopback interface anyway).
