### ISSUE TITLE
Support more colors

### ISSUE THREAD

**Issue by sarnobat** [garabik/grc#26]
As far as I know, the only colors that are supported are:

black, green, yellow, blue, magenta, cyan, white

Is it possible to support a wider spectrum of colors? 256 colors would be great.

**Comment by derimagia** [comment]
Colors are here: https://github.com/garabik/grc/blob/master/grcat#L15

**Comment by sarnobat** [comment]
So no more colors are supported? I was trying to modify the escape codes to other colors but the escape sequences just get printed verbatim. Should they work?

**Comment by derimagia** [comment]
Read the docs in the readme, "Yet another special name is an arbitrary string enclosed in straight quotes. This string will be inserted directly into the output in front of the matching expression. The string will be eval'ed, so you can use usual python escape sequences.

This is useful on a 256-colour enabled xterm, where e.g. colours="\033[38;5;22m" will give you a dark green (inspired by Rutger Ovidius). Caveat: the string cannot contain a comma. This is due to my laziness :-)"

**Comment by sarnobat** [comment]
Okay great, thank you. You may close the ticket.
