### ISSUE TITLE
disable colorful outputs when stdout/stderr is not tty

### ISSUE THREAD

**Issue by amosbird** [garabik/grc#66]
`grc.fish` breaks a lot of commands when using in interactive fish shell, such as `grep` and `systemctl`

**Comment by urxvtcd** [comment]
Hello there. I found this to be an issue too and managed to solve it. Use `eval "function $executable; if isatty stdout; grc $executable \$argv; else; command $executable \$argv; end; end"` instead of `alias $executable "grc $executable"` as is found in `grc.fish`. Yeah, this is a bit hacky, but works.

@garabik Do you want me to make a PR with this?

Also if you want to diable grc in scripts (this caused me some trouble) you can wrap the whole for loop in `grc.fish` in an if statement like `if status --is-interactive`.

Cheers!

**Comment by urxvtcd** [comment]
D'oh! RTFM. grc has `--colour=auto` option which fixes exactly this issue. Though maybe it should be default or run this way in `grc.fish`?

**Comment by garabik** [comment]
Or even better, it should be a default for `grc`. Fixed in d0420ed646fc7bf9f54fdcb537803c8d9a2da101.

**Comment by windware-ono** [comment]
This breaks anything that goes through a pipe.
`grc ip a` (This is colored as it should)
but
`grc ip a | less -R`  (This breaks the coloring because `isatty` returns false)

I figured all the colorings that was piped through `less` broke when Ubuntu 20.04 had this "fix" in their grc package.
